### ISSUE TITLE
Task 13 (Dropdown and collapse)

### ISSUE THREAD

**Issue by pmvald** [Appers-lab/sss-theme#10]
dropdown
-------------------
Our goal is to make a minimalized version of bootstrap `dropdown` class (you can find this class in /bootstrap5/_dropdown.scss). Create a new class `dropdown` in `/layouts/_dropdown.scss` and replace importing the boostrsap dropdown in _layouts.scss with this file (yes, dropdown is considered as a layout class).

follow the following html boilerplate:

```html
<div class="dropdown"
  <!-- this can be any inline-block element: <a>, <span>, <button>, etc. -->
   <a class="dropdown__toggle">link</a>
   <section class="dropdown__content">
     <!-- any content here, add no style to them -->
   </section>
</div>
```

In the above composition, the `dropdown__content` element should be hidden. When the dropdown is open, the javascript will add the modifier `--open` to both the toggle and the wrapper (i.e., `dropdown__toggle--open` and `dropdown__content--open`)

You don't need to worry about the javascript part, just implement the css for the case when these modifier is added. In this case, the __content section should appear (like `display: block`) and basically that's it!

But then extend the dropdown class in layer 1 to add more opinionated styles to it. So create a file in `/styles/_dropdown.scss` and further add:
- a *caret* symbol at the end of the toggle text (same as bootstrap) . 
- when opening the content, an animation on its height (something like folding from top to bottom.) 

*Note:* the __content section should be `position:absolute`. You may have difficulty figuring out what value you have to use for the `top` style. Because the top value depends on the height of the __toggle section. For now, use `2rem` for the layer 0 style and for layer 1 style use the same height as any link in the `<menu>` (see styles in `/styles/_menu.scss`). See if you can calculate this height in a modular way only in terms of `<menu>` height (something like `1rem+$menu-link-padding`?)

Make an html demo of your dropdown in /tasks/task-013 folder. To run your demo just make a dummy button and write a simple javascript code that open/closes your dropdown when you click the dummy button (note that this button and the javascript will not be part of final product, it is only to demonstrate the design and its animation, so take it easy!) For your demo, you can use the `<menu class="menu--column">` for the content part to make a column menu. 

collapse
-----------------------
collapse is similar to dropdown, except that the __content part is not absolute and once it opens in pushed anything below it down (refer to bootstrap collapse to get an idea what it is). Follow the same route as you did for the dropdown. Define the minimal layer 0 style in `/layouts/_collapse.scss` and the more fancy opinionated styles (including animations) in `/styles/_collapse.scss`

The html boilerplate is:

```html
<div class="collapse"
  <!-- any content can be here - do not add any style to anything here -->

  <!-- toggle can be any block-inline element -->
   <a class="collapse__toggle"></a>
   <section class="collapse__content">
     <!-- any content here, add no style to them -->
   </section>
</div>
```

To open the collapse the modifier `--open` will be added to togle and content parts. Note that the layer 0 style is pretty much the same as dropdown, but for the layer 1 style make these distinctions:

- add a right arrow symbol to the __toggle content (like >)
- without --open modifier, the __content is hidden
- when --open modifier is added:
  * the __toggle content (> symbol) will animated to rotate 90 degree to become (v)
  * the __content will be shown by a sliding top-bottom animation.
  
Keep it minimal and do not add any other style to anything else.

Make an html demo of your collapse in /tasks/task-013 folder.

**Comment by navjot-chahal** [comment]
@pmvald  I have started on this task a few days ago and it's almost complete, but I have few questions before I make a pull request.

- Upon applying transition animation to the `dropdown__content` and not to any of its content i.e. `menu class="menu--column"` I see only the container doing the animation and its content appearing instantly without animation. I think that an additional class should be added to the content of the like `"dropdown__items"` to style content of the dropdown individually. Please advise.
- The `dropdown__toggle` includes a caret symbol. Do you want it to change to `caret(end)` upon dropdown?
- What should be in `dropdown__toggle--open` class? Should it be empty for now?
