### ISSUE TITLE
Task 32 (checkbox/radiobox solution)

### ISSUE THREAD

**Issue by pmvald** [Appers-lab/sss-theme#50]
Prerequisite: 
- [design guide](http://appers-lab.com/guides/design-system) 
- [mobile design guide](http://appers-lab.com/guides/mobile-design-system) 
- [web component guide](http://appers-lab.com/guides/web-component/)

The task folder (/tasks/task-032.js) contains js code for checkbox and radiobox components. Note that these js files are modules that export classes/functions, but for this task you can just copy them directly into the demo html file and remove the export statement. 

For the radiobox component note that there are two classes: RadioBox and RadioBoxGroup (the meaning should be clear). In this design task we only need the RadioBox. After registering this class into a custom element called `radio-box` you can just create a group of three radioboxes like:

```html
<radio-box group="my-group" value="1">Option 1</radio-box>
<radio-box group="my-group" value="2">Option 2</radio-box>
<radio-box group="my-group" value="3">Option 3</radio-box>
```

Note that these components are styled using css variables and also `::part`.  

Styling the box
-----------------------
We need to improve the styling of the box section of these components when they are are active (=selected). In particular, the radiobox style is just a filled circle which is terrible. Right now the idea is when the component becomes active a `<div>` inside the box is displayed (by changing its `display:none` to `display:block`) and we tried to show a character in the center of this div. Alternatively you can show an svg (with inline code) for the active/inactive cases (just make sure that the color for the active case comes from the relevant css variable). See how you can make these check/radio boxes look better

check/radiobox in mobile listview
-------------------------------------------------
Now we want to style radiobox/checkbox similar to Mobilekit > Components > Checkboxes (List Example section) and Mobilekit > Components > Radio (List Example section)

To do so, define classes `s-checkbox-list` and `s-radiobox-list` (in _inputs.m.scss). These classes should style a list of checkbox or radioboxes using their css variables and/or `::part` (probably `::part` gives you more freedom). The html boilerplate is something like

checkbox list
```html
<ul class="s-checkbox-list">
<li><check-box>Option 1 </check-box></li>
<li><check-box>Option 2 </check-box></li>
<li><check-box>Option 3 </check-box></li>
<ul>
```

radiobox list
```html
<ul class="s-checkbox-list">
<li><radio-box group="group1">Option 1 </radio-box></li>
<li><radio-box group="group1">Option 2 </radio-box></li>
<li><radio-box group="group1">Option 3 </radio-box></li>
<ul>
```

**Comment by j-ae** [comment]
@pmvald, you made them at tasks/task-31.

Please re-name the folder.

**Comment by pmvald** [comment]
@j-ae You can rename it, we won't touch it

**Comment by j-ae** [comment]
@pmvald,

_**To do so, define classes s-checkbox-list and s-radiobox-list (in _inputs.m.scss).**_ 
We already have _inputs.scss. Do I need to make _inputs.m.scss?

**Comment by pmvald** [comment]
@j-ae .m files are those that are specifically for the mobile. But now I'm thinking that we make these styles in styles/_lists.m.scss - for they are more of the nature of list view than just inputs ...
